[package]
name = "simple-version-tracker"

version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "3.0.10", features = ["derive"] }
serde = { version = "1.0.132", features = ["derive"] }
serde_yaml = { version = "0.8.23" }
