run:
  go: "1.19"

  timeout: "10m"
  issues-exit-code: 1

  skip-dirs:
    - "vendor"

linters:
  fast: false
  enable-all: true

  disable:
    - lll
    - wsl
    - nlreturn
    - varnamelen
    - exhaustruct
    - exhaustivestruct
    - gochecknoglobals
    - goerr113
    - gomnd
    - goprintffuncname
    - tagliatelle
    - nosnakecase

linters-settings:
  gci:
    sections:
      - standard
      - default
      - Prefix(github.com/denis96z/simple-version-tracker/worker)

  funlen:
    lines: 80

  cyclop:
    max-complexity: 15

  gocyclo:
    min-complexity: 15

  exhaustive:
    default-signifies-exhaustive: true
